#-------------------------------------------------------------------------
#
# Makefile
#    Makefile for access/sequence
#
# IDENTIFICATION
#    src/backend/access/sequence/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/sequence
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = local.o sequence.o sequenceamapi.o

include $(top_srcdir)/src/backend/common.mk
