#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/no_storage
#
# IDENTIFICATION
#    src/backend/access/no_storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/no_storage
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	no_storage_handler.o

include $(top_srcdir)/src/backend/common.mk
